name: kiv_mbkz_weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  http: ^0.12.0
  equatable: ^1.0.0
  intl: ^0.16.1
  simple_animations: ^1.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
